### ISSUE TITLE
Crash log. 

### ISSUE THREAD

**Issue by IceLancerSR** [alexsylex/AnimationMotionRevolution#1]
Hello! 
This is probably some skysa_ ->amr converted animation that went bad. 
I am hoping that there is a way to narrow it down and help me pinpoint which one.
Thanks

[Crash_2021_9_10_0-18-3.txt](https://github.com/alexsylex/AnimationMotionRevolution/files/7142407/Crash_2021_9_10_0-18-3.txt)
[Crash_2021_9_10_0-18-3(2).txt](https://github.com/alexsylex/AnimationMotionRevolution/files/7142410/Crash_2021_9_10_0-18-3.2.txt)

CastOKStart = zero?

**Comment by alexsylex** [comment]
Sorry for the late response, the first log is very similar to other report in the nexus, but the second one is very weird (all zeroes in the stack???) .NET Script Framework received an update where meh321 improved the generation of the log, because sometimes there was missing information, could you update and post another log?

Also in what situation happened the crashes?

**Comment by IceLancerSR** [comment]
> Does it happen after hours of gameplay or sometimes happens in a short amount of time? I want to know it because maybe the CTD happens after encountering a great number of fighting NPCs.
> 
> The other user that reported the log similar to yours said that it happened when "running towards the last wave of a bunch of bandits that attack Whiterun" in a mod quest.

Sorry for late reply.
I understand that every info is crucial but this is just too random. I cant seem to find pattern. Sometimes it happens with just 2 npc , sometimes with bunch of them. 
One thing crossed my mind tho, now that i think of it. But its probably a fluke. So far all crashes that happened were on first engagement of enemy. Not in middle of combat.

**Comment by alexsylex** [comment]
Ok, I will try to replicate the problems.

In the mean time, I am doing some "quality of code" improvements with some research I've done about memory management, because in the log I have seen something potentially wrong with how the motion data is mapped to the characters.

> .NET Script Framework received an update where meh321 improved the generation of the log, because sometimes there was missing information, could you update and post another log?

Could you please?

**Comment by IceLancerSR** [comment]
> Ok, I will try to replicate the problems.
> 
> In the mean time, I am doing some "quality of code" improvements with some research I've done about memory management, because in the log I have seen something potentially wrong with how the motion data is mapped to the characters.
> 
> > .NET Script Framework received an update where meh321 improved the generation of the log, because sometimes there was missing information, could you update and post another log?
> 
> Could you please?

Yes ofc updated it some time ago.

**Comment by alexsylex** [comment]
Ok, time to add .ini options for AMR logs I guess :)

> Yes ofc updated it some time ago.

Hmm the crashlogs have FrameworkVersion: 12 and GameLibraryVersion: 17, while last .Net Script Framework creates logs with FrameworkVersion: 14 and GameLibraryVersion: 18.

Can you quick verify that you have the version of 11 September (v17)?

**Comment by IceLancerSR** [comment]
> Ok, time to add .ini options for AMR logs I guess :)
> 
> > Yes ofc updated it some time ago.
> 
> Hmm the crashlogs have FrameworkVersion: 12 and GameLibraryVersion: 17, while last .Net Script Framework creates logs with FrameworkVersion: 14 and GameLibraryVersion: 18 for me.
> 
> Can you quick verify that you have the version of 11 September (v17)?

I just didn't play since then.

**Comment by alexsylex** [comment]
With the current version the out of memory issues are handled as an exception.
