### ISSUE TITLE
Code license?

### ISSUE THREAD

**Issue by alandtse** [alexsylex/AnimationMotionRevolution#2]
Hi, what license are you distributing this code under? I'm considering a VR port but right now your code doesn't provide any license that I can see.

Your vcpkg.json says MIT but it's not clear to me it's intentional. https://github.com/alexsylex/AnimationMotionRevolution/blob/main/vcpkg.json#L6

https://choosealicense.com/

**Comment by alexsylex** [comment]
Hi, I had the port in mind for the next version. My plans are updating to AE with a port to VR and support for the SE versions (at least for the moment). 

With respect to the license, yes, that is a template... This is my first project so I'm really newbie to this kind of things 😅. I think GPLv3 fits most my intentions for this plugin, so I will add the LICENSE file to the repo. Thanks a lot for the info! 😄
