### ISSUE TITLE
VR port

### ISSUE THREAD

**Issue by alandtse** [alexsylex/AnimationMotionRevolution#3]
FYI, I believe I have a working VR port but noticed you're working on it so haven't released it (also I'm not sure of a good animation test case to confirm it's working). I noticed you were working on AE/VR integration, so haven't sent any PRs since your code is in flux. Happy to send you PRs once you have any structural changes locked down. 

I thought I'd warn you of one bug that may impact your AE port that I found while working on the VR port to save you some time. The way you pull the register r13 [here](https://github.com/alexsylex/AnimationMotionRevolution/blob/main/source/Hooks.cpp#L334-L346) can result in bad data. Took me a while to hunt it down but in VR, r13 gets overwritten somehow before the `mov` due to the xbyak function call.

I ended up just passing it on the stack by modifying the [hook](https://github.com/alexsylex/AnimationMotionRevolution/blob/main/include/Hooks.h#L147-L159). It looks like you tried that at some point but moved away from it.

```cpp
HookCode(std::uintptr_t a_hookFunc, std::uintptr_t return_address)
                {
                    Xbyak::Label hookLabel;
                    Xbyak::Label retnLabel;

                    sub(rsp, 0x30);
                    mov(ptr[rsp+0x20], r13); // r13 = Character* as argument 5
                    mov(r9, rbx);                // rbx = BSFixedString*    as argument 4
                    call (ptr[rip + hookLabel]);
                    add(rsp, 0x30);
                    mov(rax, return_address+5);
                    jmp(rax);
                    L(hookLabel);
                    dq(a_hookFunc);
                }

```
I noticed you added my CommonLibVR. I've already added all your IDs into VR Address Library so no need to discover VR offsets.

Let me know if you'd prefer to host the VR port on your official page or if I should just create a VR page that splits DP with you 50/50 like I do for other authors. I tend to do the page if the author has mentioned they'd prefer someone else handle the VR support.

Regardless, thanks again for releasing your mod open source.

**Comment by alexsylex** [comment]
Yes, I didn't manage to pass the 5th argument in the stack 😅... Stack rules for arguments were unknown to me. So you need to reserve 8 bytes per argument even if they are registers... and the stack has to be 16-byte aligned (I read that somewhere), isn't it?

I would prefer to host the VR port in my page, thanks for offering. Of course I'm crediting you for the help and CommonLibVR.

**Comment by alandtse** [comment]
I saw you finished the VR port. Congrats! I'll rebase on it and may offer PRs if I see any bugs.
